In [1]:
import pandas as pd

df = pd.read_csv("../1.Raw_data/Delivery_Logistics.csv")

In [2]:
df.head()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,250.99,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000008,no,delivered,3,1632.7206
1,250.99,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,no,delivered,5,640.1700
2,250.99,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000016,no,delivered,4,1448.1700
3,250.99,dhl,electronics,ev van,same day,east,cold,269.7,12.69,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000008,no,delivered,3,1486.5700
4,250.99,dhl,clothing,van,two day,north,foggy,256.7,37.02,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000016,no,delivered,4,1394.5600

In [3]:
df.dtypes

delivery_id            float64
delivery_partner           str
package_type               str
vehicle_type               str
delivery_mode              str
region                     str
weather_condition          str
distance_km            float64
package_weight_kg      float64
delivery_time_hours        str
expected_time_hours        str
delayed                    str
delivery_status            str
delivery_rating          int64
delivery_cost          float64
dtype: object

In [4]:
df[["delivery_time_hours", "expected_time_hours"]].head(10)

             delivery_time_hours            expected_time_hours
0  1970-01-01 00:00:00.000000008  1970-01-01 00:00:00.000000008
1  1970-01-01 00:00:00.000000002  1970-01-01 00:00:00.000000003
2  1970-01-01 00:00:00.000000010  1970-01-01 00:00:00.000000016
3  1970-01-01 00:00:00.000000006  1970-01-01 00:00:00.000000008
4  1970-01-01 00:00:00.000000009  1970-01-01 00:00:00.000000016
5  1970-01-01 00:00:00.000000004  1970-01-01 00:00:00.000000002
6  1970-01-01 00:00:00.000000006  1970-01-01 00:00:00.000000008
7  1970-01-01 00:00:00.000000004  1970-01-01 00:00:00.000000008
8  1970-01-01 00:00:00.000000005  1970-01-01 00:00:00.000000008
9  1970-01-01 00:00:00.000000003  1970-01-01 00:00:00.000000008

In [5]:
df["delivery_id"].head(20)

0     250.99
1     250.99
2     250.99
3     250.99
4     250.99
5     250.99
6     250.99
7     250.99
8     250.99
9     250.99
10    250.99
11    250.99
12    250.99
13    250.99
14    250.99
15    250.99
16    250.99
17    250.99
18    250.99
19    250.99
Name: delivery_id, dtype: float64

In [6]:
df["delivery_id"].nunique()

24502

In [7]:
df["delivery_id"].value_counts().head(10)

delivery_id
250.99      250
24750.01    250
251.00        1
252.00        1
253.00        1
254.00        1
255.00        1
256.00        1
257.00        1
258.00        1
Name: count, dtype: int64

In [8]:
df["delivery_id"].iloc[240:260]

240    250.99
241    250.99
242    250.99
243    250.99
244    250.99
245    250.99
246    250.99
247    250.99
248    250.99
249    250.99
250    251.00
251    252.00
252    253.00
253    254.00
254    255.00
255    256.00
256    257.00
257    258.00
258    259.00
259    260.00
Name: delivery_id, dtype: float64

In [9]:
df["delivery_id"].iloc[-260:]

24740    24741.00
24741    24742.00
24742    24743.00
24743    24744.00
24744    24745.00
           ...
24995    24750.01
24996    24750.01
24997    24750.01
24998    24750.01
24999    24750.01
Name: delivery_id, Length: 260, dtype: float64

In [10]:
df.shape

(25000, 15)

In [11]:
df.tail()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
24995,24750.01,dhl,furniture,scooter,two day,east,foggy,80.7,3.65,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000016,no,delivered,5,414.45
24996,24750.01,ecom express,automobile parts,ev van,standard,west,clear,172.9,21.42,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000024,no,delivered,5,928.76
24997,24750.01,ekart,clothing,scooter,same day,east,rainy,168.4,4.85,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000008,yes,delayed,2,956.55
24998,24750.01,shadowfax,documents,ev van,standard,west,stormy,37.2,8.04,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000024,no,delivered,5,210.12
24999,24750.01,blue dart,pharmacy,ev bike,two day,central,rainy,279.3,5.06,1970-01-01 00:00:00.000000007,1970-01-01 00:00:00.000000016,no,delivered,3,1411.68

In [12]:
df.isnull().sum()

delivery_id            0
delivery_partner       0
package_type           0
vehicle_type           0
delivery_mode          0
region                 0
weather_condition      0
distance_km            0
package_weight_kg      0
delivery_time_hours    0
expected_time_hours    0
delayed                0
delivery_status        0
delivery_rating        0
delivery_cost          0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df["region"].value_counts()

region
west       5095
central    5060
south      4977
north      4949
east       4919
Name: count, dtype: int64

In [15]:
df["delivery_partner"].value_counts()

delivery_partner
xpressbees          2826
fedex               2818
dhl                 2802
ekart               2801
blue dart           2798
delhivery           2786
shadowfax           2736
ecom express        2722
amazon logistics    2711
Name: count, dtype: int64

In [16]:

df["package_type"].value_counts()

package_type
fragile items       2848
pharmacy            2810
documents           2805
automobile parts    2795
electronics         2792
clothing            2767
furniture           2746
cosmetics           2744
groceries           2693
Name: count, dtype: int64

In [17]:
df["vehicle_type"].value_counts()

vehicle_type
ev bike    4218
van        4187
scooter    4174
bike       4160
truck      4145
ev van     4116
Name: count, dtype: int64

In [18]:
df["delivery_mode"].value_counts()

delivery_mode
two day     6302
same day    6279
express     6233
standard    6186
Name: count, dtype: int64

In [19]:
df["weather_condition"].value_counts()

weather_condition
foggy     4219
stormy    4198
rainy     4171
cold      4158
hot       4130
clear     4124
Name: count, dtype: int64

In [20]:
df["delayed"].value_counts()

delayed
no     18331
yes     6669
Name: count, dtype: int64

In [21]:
df["delivery_status"].value_counts()

delivery_status
delivered    18331
delayed       5341
failed        1328
Name: count, dtype: int64

In [22]:
pd.crosstab(df["delivery_status"], df["delayed"])

delayed             no   yes
delivery_status
delayed              0  5341
delivered        18331     0
failed               0  1328

In [23]:
df["delivery_rating"].value_counts().sort_index()

delivery_rating
1     920
2    3602
3    5773
4    7318
5    7387
Name: count, dtype: int64

In [24]:
df["distance_km"].describe()

count    25000.000000
mean       150.390436
std         86.409745
min          3.600000
25%         75.900000
50%        151.000000
75%        224.900000
max        297.100000
Name: distance_km, dtype: float64

In [25]:
df["package_weight_kg"].describe()

count    25000.000000
mean        25.145898
std         14.368663
min          0.670000
25%         12.680000
50%         25.145000
75%         37.660000
max         49.520000
Name: package_weight_kg, dtype: float64

In [26]:
df["delivery_cost"].describe()

count    25000.000000
mean       864.944579
std        435.712593
min         95.667400
25%        490.800000
50%        867.535000
75%       1237.910000
max       1632.720600
Name: delivery_cost, dtype: float64

COLUMNS ARE VERIFIED , NOW WE HAVE TO CHECK THE DELIVERY TIMES..

In [27]:
df["delivery_time_hours"].iloc[0]

'1970-01-01 00:00:00.000000008'

In [28]:
df["delivery_time_hours"].head(20)

0     1970-01-01 00:00:00.000000008
1     1970-01-01 00:00:00.000000002
2     1970-01-01 00:00:00.000000010
3     1970-01-01 00:00:00.000000006
4     1970-01-01 00:00:00.000000009
5     1970-01-01 00:00:00.000000004
6     1970-01-01 00:00:00.000000006
7     1970-01-01 00:00:00.000000004
8     1970-01-01 00:00:00.000000005
9     1970-01-01 00:00:00.000000003
10    1970-01-01 00:00:00.000000005
11    1970-01-01 00:00:00.000000003
12    1970-01-01 00:00:00.000000008
13    1970-01-01 00:00:00.000000006
14    1970-01-01 00:00:00.000000012
15    1970-01-01 00:00:00.000000008
16    1970-01-01 00:00:00.000000010
17    1970-01-01 00:00:00.000000011
18    1970-01-01 00:00:00.000000004
19    1970-01-01 00:00:00.000000007
Name: delivery_time_hours, dtype: str

In [29]:
delivery_time_test = pd.to_datetime(df["delivery_time_hours"])

In [30]:
delivery_time_test.dt.nanosecond.head(20)

0      8
1      2
2     10
3      6
4      9
5      4
6      6
7      4
8      5
9      3
10     5
11     3
12     8
13     6
14    12
15     8
16    10
17    11
18     4
19     7
Name: delivery_time_hours, dtype: int32

In [31]:
delivery_time_test.dt.nanosecond.describe()

count    25000.000000
mean         6.248040
std          3.140935
min          0.000000
25%          4.000000
50%          6.000000
75%          8.000000
max         19.000000
Name: delivery_time_hours, dtype: float64

In [32]:
(df["delivery_time_hours"].apply(lambda x: pd.to_datetime(x).nanosecond) == 0).sum()

np.int64(255)

In [33]:

delivery_time_hours_test = (
    pd.to_datetime(df["delivery_time_hours"])
    - pd.Timestamp("1970-01-01")
).dt.total_seconds() / 3600

delivery_time_hours_test.describe()

count    2.500000e+04
mean     1.735567e-12
std      8.724819e-13
min      0.000000e+00
25%      1.111111e-12
50%      1.666667e-12
75%      2.222222e-12
max      5.277778e-12
Name: delivery_time_hours, dtype: float64

In [34]:
delivery_time_recovered = delivery_time_test.dt.nanosecond

In [35]:
delivery_time_recovered.describe()

count    25000.000000
mean         6.248040
std          3.140935
min          0.000000
25%          4.000000
50%          6.000000
75%          8.000000
max         19.000000
Name: delivery_time_hours, dtype: float64

In [36]:
(delivery_time_recovered == 0).sum()

np.int64(255)

In [37]:
delivery_time_recovered.value_counts().sort_index()

delivery_time_hours
0      255
1      963
2     1668
3     2352
4     2571
5     3011
6     3118
7     2921
8     2386
9     1875
10    1371
11    1039
12     649
13     371
14     247
15     116
16      51
17      26
18       7
19       3
Name: count, dtype: int64

In [38]:
expected_time_test = pd.to_datetime(df["expected_time_hours"])

expected_time_recovered = expected_time_test.dt.nanosecond

expected_time_recovered.describe()

count    25000.000000
mean        13.107680
std          7.559024
min          2.000000
25%          8.000000
50%          8.000000
75%         16.000000
max         24.000000
Name: expected_time_hours, dtype: float64

In [39]:
expected_time_recovered.value_counts().sort_index()

expected_time_hours
2     1015
3     1029
4     1037
5     1080
6     1013
7     1051
8     6287
16    6302
24    6186
Name: count, dtype: int64

In [40]:
pd.crosstab(df["delivery_mode"], expected_time_recovered)

expected_time_hours    2     3     4     5     6     7     8     16    24
delivery_mode
express              1015  1029  1037  1080  1013  1051     8     0     0
same day                0     0     0     0     0     0  6279     0     0
standard                0     0     0     0     0     0     0     0  6186
two day                 0     0     0     0     0     0     0  6302     0

In [41]:
df_clean = df.copy()

In [42]:
df_clean["delivery_id"] = range(1, len(df_clean) + 1)

In [43]:
df_clean.head()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,1,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000008,no,delivered,3,1632.7206
1,2,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,no,delivered,5,640.1700
2,3,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000016,no,delivered,4,1448.1700
3,4,dhl,electronics,ev van,same day,east,cold,269.7,12.69,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000008,no,delivered,3,1486.5700
4,5,dhl,clothing,van,two day,north,foggy,256.7,37.02,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000016,no,delivered,4,1394.5600

In [44]:
df_clean.tail()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
24995,24996,dhl,furniture,scooter,two day,east,foggy,80.7,3.65,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000016,no,delivered,5,414.45
24996,24997,ecom express,automobile parts,ev van,standard,west,clear,172.9,21.42,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000024,no,delivered,5,928.76
24997,24998,ekart,clothing,scooter,same day,east,rainy,168.4,4.85,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000008,yes,delayed,2,956.55
24998,24999,shadowfax,documents,ev van,standard,west,stormy,37.2,8.04,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000024,no,delivered,5,210.12
24999,25000,blue dart,pharmacy,ev bike,two day,central,rainy,279.3,5.06,1970-01-01 00:00:00.000000007,1970-01-01 00:00:00.000000016,no,delivered,3,1411.68

In [45]:
df_clean["delivery_time_hours"] = delivery_time_recovered

In [46]:
df_clean["expected_time_hours"] = expected_time_recovered

In [47]:
df_clean[[
    "delivery_time_hours",
    "expected_time_hours"
]].head(10)

   delivery_time_hours  expected_time_hours
0                    8                    8
1                    2                    3
2                   10                   16
3                    6                    8
4                    9                   16
5                    4                    2
6                    6                    8
7                    4                    8
8                    5                    8
9                    3                    8

In [48]:
df_clean.head(20)

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,1,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,8,8,no,delivered,3,1632.7206
1,2,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,2,3,no,delivered,5,640.1700
2,3,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,10,16,no,delivered,4,1448.1700
3,4,dhl,electronics,ev van,same day,east,cold,269.7,12.69,6,8,no,delivered,3,1486.5700
4,5,dhl,clothing,van,two day,north,foggy,256.7,37.02,9,16,no,delivered,4,1394.5600
5,6,amazon logistics,documents,ev bike,express,west,rainy,48.4,33.15,4,2,yes,delayed,3,391.4500
6,7,delhivery,groceries,scooter,same day,central,clear,198.3,43.79,6,8,no,delivered,3,1222.8700
7,8,xpressbees,fragile items,van,same day,north,cold,114.6,42.63,4,8,no,delivered,3,800.8900
8,9,blue dart,clothing,van,same day,south,hot,142.4,14.06,5,8,no,delivered,5,854.1800
9,10,delhivery,pharmacy,truck,same day,east,foggy,47.1,29.28,3,8,no,delivered,5,423.3400
10,11,fedex,groceries,scooter,same day,east,cold,293.2,22.05,5,8,no,delivered,4,1632.1500
11,12,ecom express,electronics,truck,two day,east,cold,80.4,46.48,3,16,no,delivered,5,541.4400
12,13,xpressbees,pharmacy,ev van,two day,north,rainy,257.7,20.56,8,16,no,delivered,4,1350.1800
13,14,xpressbees,cosmetics,bike,express,east,stormy,19.0,3.36,6,2,yes,failed,1,155.0800
14,15,xpressbees,automobile parts,ev bike,two day,east,stormy,237.9,24.59,12,16,no,delivered,3,1263.2700
15,16,amazon logistics,furniture,ev van,express,north,hot,239.3,11.67,8,6,yes,delayed,3,1281.5100
16,17,fedex,documents,bike,standard,west,stormy,79.0,0.73,10,24,no,delivered,5,397.1900
17,18,blue dart,fragile items,ev bike,standard,central,rainy,170.7,45.62,11,24,no,delivered,5,990.3600
18,19,amazon logistics,documents,van,same day,north,rainy,90.0,33.70,4,8,no,delivered,3,651.1000
19,20,fedex,cosmetics,truck,express,north,rainy,64.0,6.03,7,3,yes,failed,2,388.0900

In [49]:
df_clean["delivery_time_hours"] = df_clean["delivery_time_hours"].astype(int)
df_clean["expected_time_hours"] = df_clean["expected_time_hours"].astype(int)
df_clean["delivery_id"] = df_clean["delivery_id"].astype(int)
df_clean["delivery_rating"] = df_clean["delivery_rating"].astype(int)

In [50]:
df_clean.dtypes

delivery_id              int64
delivery_partner           str
package_type               str
vehicle_type               str
delivery_mode              str
region                     str
weather_condition          str
distance_km            float64
package_weight_kg      float64
delivery_time_hours      int64
expected_time_hours      int64
delayed                    str
delivery_status            str
delivery_rating          int64
delivery_cost          float64
dtype: object

In [51]:
print("Shape:", df_clean.shape)
print("Missing values:", df_clean.isnull().sum().sum())
print("Duplicate rows:", df_clean.duplicated().sum())
print("Duplicate IDs:", df_clean["delivery_id"].duplicated().sum())

Shape: (25000, 15)
Missing values: 0
Duplicate rows: 0
Duplicate IDs: 0

In [52]:
df_clean.to_csv("delivery_logistics_cleaned.csv", index=False)

In [53]:
import os

os.path.exists("delivery_logistics_cleaned.csv")

True

In [54]:
os.getcwd()

'e:\\PROJECT-LDP\\3.Python'

In [55]:
print("Shape:", df_clean.shape)
print("Missing values:", df_clean.isnull().sum().sum())
print("Duplicate rows:", df_clean.duplicated().sum())
print("Duplicate IDs:", df_clean["delivery_id"].duplicated().sum())

Shape: (25000, 15)
Missing values: 0
Duplicate rows: 0
Duplicate IDs: 0

In [56]:
df_clean.head(100)

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,1,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,8,8,no,delivered,3,1632.7206
1,2,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,2,3,no,delivered,5,640.1700
2,3,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,10,16,no,delivered,4,1448.1700
3,4,dhl,electronics,ev van,same day,east,cold,269.7,12.69,6,8,no,delivered,3,1486.5700
4,5,dhl,clothing,van,two day,north,foggy,256.7,37.02,9,16,no,delivered,4,1394.5600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,ekart,clothing,van,two day,east,foggy,174.3,47.29,10,16,no,delivered,5,1013.3700
96,97,ekart,groceries,bike,same day,west,clear,11.4,40.22,1,8,no,delivered,5,277.6600
97,98,xpressbees,electronics,ev van,express,east,clear,166.4,44.96,6,5,yes,delayed,2,1016.8800
98,99,shadowfax,cosmetics,van,standard,west,stormy,189.6,38.07,11,24,no,delivered,5,1062.2100
99,100,blue dart,groceries,truck,express,west,stormy,111.2,37.33,6,4,yes,delayed,2,717.9900

In [57]:
df_clean.head(10)

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,1,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,8,8,no,delivered,3,1632.7206
1,2,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,2,3,no,delivered,5,640.1700
2,3,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,10,16,no,delivered,4,1448.1700
3,4,dhl,electronics,ev van,same day,east,cold,269.7,12.69,6,8,no,delivered,3,1486.5700
4,5,dhl,clothing,van,two day,north,foggy,256.7,37.02,9,16,no,delivered,4,1394.5600
5,6,amazon logistics,documents,ev bike,express,west,rainy,48.4,33.15,4,2,yes,delayed,3,391.4500
6,7,delhivery,groceries,scooter,same day,central,clear,198.3,43.79,6,8,no,delivered,3,1222.8700
7,8,xpressbees,fragile items,van,same day,north,cold,114.6,42.63,4,8,no,delivered,3,800.8900
8,9,blue dart,clothing,van,same day,south,hot,142.4,14.06,5,8,no,delivered,5,854.1800
9,10,delhivery,pharmacy,truck,same day,east,foggy,47.1,29.28,3,8,no,delivered,5,423.3400